project:
  type: book

book:
  title: "Digitale Archäologie"
  subtitle: "Werkzeuge und Konzepte im Wandel"
  author:
    - name: Maria Shinoto
  date: "2023-09-26"
  date-format: long
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - overview.qmd
    - part: archaeology.qmd
      chapters:
        - historical-stages.qmd
        - actual-situation.qmd
        - non-research-work.qmd
        - outlook-discussion.qmd
    - part: computational-basics.qmd
      chapters:
        - hardware.qmd
        - software.qmd
        - community.qmd
        - methods.qmd
        - standards-qualifications.qmd
    - part: levels-for-teaching.qmd
      chapters:
        - foundations.qmd
        - applications.qmd
    - part: implementations-examples.qmd
      chapters:
        - datamodeling.qmd
        - writing.qmd
        - cooperation.qmd
    - references.qmd
  appendices:
    - list.qmd
lang: de
bibliography: references.bib

format:
  html:
    theme: cosmo  
  pdf:
    documentclass: scrreprt