project:
  type: book

book:
  title: "Digitale Archäologie"
  author: "Maria Shinoto"
  date: "2023-09-26"
  date-format: long
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - intro-archaeological-work.qmd
        - intro-overview.qmd
    - part: history.qmd
      chapters: 
        - history-stages.qmd
        - history-actualsituation.qmd
        - history-nonresearchwork.qmd
        - history-outlookdiscussion.qmd
    - part: basics.qmd
      chapters: 
        - basics-hardware.qmd
        - basics-software.qmd
        - basics-consistency.qmd
        - basics-community.qmd
        - basics-methods.qmd
        - basics-standards-qualifications.qmd
    - part: teaching.qmd
      chapters: 
        - teaching-foundations.qmd
        - teaching-applications.qmd
    - part: implementations-examples.qmd
      chapters: 
        - implementation-writing.qmd
        - implementation-cooperation.qmd
        - implementation-datamodeling.qmd
    - references.qmd

lang: de

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    papersize: a4
  docx: default