project:
  type: book

book:
  title: "Digitale Archäologie"
  subtitle: "Orientierung in ständigem Wandel"
  author: "Maria Shinoto"
  date: "2023-09-11"
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
lang: de
bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt

editor: visual

