project:
  type: book

book:
  title: "Digitale Archäologie"
  # subtitle: "-- v0.0.0.1 --"
  author: "Maria Shinoto"
  date: last-modified
  date-format: long
 # license: CC BY-SA
  repo-url: https://github.com/mariashinoto/digitialarchaeology.de
  reader-mode: false
  page-footer:
    left: |
      Version 0.0.0.1, Creative Commons Attribution 4.0 International</br>
      <a href=https://doi.org/10.5281/zenodo.8342717)>DOI: https://doi.org/10.5281/zenodo.8342717</a>
      
    # right: |
    #    <a href=https://zenodo.org/badge/689810268.svg)>DOI </a>
       
  # cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://mariashinoto.github.io/digitialarchaeology.de/
  # repo-url: https://github.com/hadley/r4ds/
  # repo-branch: main
  # repo-actions: [edit, issue]


  # sidebar: 
  #   tools: 
  #     - icon: github
  #       text: "Source"
  #       href: https://github.com/mariashinoto/digitialarchaeology.de
  #     - icon: fig-doi.png
  #       text: "DOI"
  #       href: https://doi.org/10.5281/zenodo.8342717
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - intro-archaeological-work.qmd
        - intro-overview.qmd
    - part: history.qmd
      chapters: 
        - history-stages.qmd
        - history-actualsituation.qmd
        - history-nonresearchwork.qmd
        - history-outlookdiscussion.qmd
    - part: basics.qmd
      chapters: 
        - basics-hardware.qmd
        - basics-software.qmd
        - basics-consistency.qmd
        - basics-community.qmd
        - basics-methods.qmd
        - basics-standards-qualifications.qmd
    - part: teaching.qmd
      chapters: 
        - teaching-foundations.qmd
        - teaching-applications.qmd
    - part: implementations-examples.qmd
      chapters: 
        - implementation-writing.qmd
        - implementation-cooperation.qmd
        - implementation-datamodeling.qmd
    - references.qmd

lang: de

bibliography: references.bib

format:
  html:
    theme: cosmo
    grid: 
      sidebar-width: 21em
  pdf:
    documentclass: scrreprt
    papersize: a4
  docx: default