project:
  type: book

book:
  title: "Digitale Archäologie"
  subtitle: "Werkzeuge und Konzepte im Wandel"
  author: "Maria Shinoto"
  date: last-modified
  date-format: long
  repo-url: https://github.com/mariashinoto/digitialarchaeology.de
  reader-mode: false
  page-footer:
    left: |
      Version 0.0.0.2, Creative Commons Attribution 4.0 International</br>
      <a href=https://doi.org/10.5281/zenodo.8342717)>DOI: https://doi.org/10.5281/zenodo.8342717</a>
  favicon: cover.jpg
  site-url: https://mariashinoto.github.io/digitialarchaeology.de/
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - intro-archaeological-work.qmd
        - intro-overview.qmd
    - part: history.qmd
      chapters: 
        - history-stages.qmd
        - history-actualsituation.qmd
        - history-nonresearchwork.qmd
        - history-outlookdiscussion.qmd
    - part: basics.qmd
      chapters: 
        - basics-hardware.qmd
        - basics-software.qmd
        - basics-consistency.qmd
        - basics-community.qmd
        - basics-methods.qmd
        - basics-standards-qualifications.qmd
    - part: teaching.qmd
      chapters: 
        - teaching-foundations.qmd
        - teaching-applications.qmd
    - part: implementations-examples.qmd
      chapters: 
        - implementation-writing.qmd
        - implementation-cooperation.qmd
        - implementation-datamodeling.qmd
    - references.qmd

lang: de

bibliography: references.bib

format:
  html:
    theme: cosmo
    grid: 
      sidebar-width: 21em
  pdf:
    documentclass: scrreprt
    papersize: a4
  docx: default