project:
  type: book

book:
  title: "Digitale Archäologie"
  subtitle: "Werkzeuge und Konzepte im Wandel"
  author:
    - name: Maria Shinoto
      # orcid: 0000-0001-6089-4526
      # affiliations:
      #   - name: Universität Heidelberg
      #     department: Philosophische Fakultät, Zentrum für Altertumswissenschaften
      #     city: Heidelberg
      #     country: Germany
      #     url: https://www.uni-heidelberg.de/fakultaeten/philosophie/zaw/ufg/mitarbeiter/shinoto_maria.html
      #   - name: 別府大学 (Beppu University)
      #     department: 文化財科学科
      #     city: 別府
      #     country: Japan
      # note: https://ac.shinoto.net (Alternative URL)
  date: "2023-09-11"
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
  sidebar:
    - logo: cover.jpg
lang: de
cover-image: cover.jpg
bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

