# Drei historische Entwicklungsstadien {#sec-history-stages}

Die Entwicklung, die man selber als Kontinuum miterlebt, wird für gewöhnlich im Nachhinein in Phasen oder Epochen eingeteilt. Ihre jeweiligen Charakteristika haben sich oft schon in den vorherigen Stufen angekündigt und wirken bis in die nachfolgenden Stufen. So sind sie nicht exclusiv nur in einer Phase anzutreffen, und auch die hier gesetzten Grenzen der Phasen in Jahreszahlen sind diskussionswürdig. Persönlich konnte ich noch die letzten Auswirkungen der ersten Stufe, die ich kurzerhand zwischen 1960 und 1990 datiere, miterleben. Während der folgenden Stadien war ich aktiv dabei, ohne damals zu verstehen, auf welchem Weg ich mich gerade befinde. Der historische Rückblick soll das Verständnis für den heutigen Zustand und die künftigen Möglichkeiten (s. @sec-actual-situation) vertiefen.

## 1960 - 1980 {#sec-history-stages-early-years}

### Akademische Nutzung

Die Entwicklung des Computers nahm während des Zweiten Weltkriegs an Fahrt auf. Die 1950er Jahre brachten die ersten wichtigen Fortschritte hin zu kommerziell initiierter Produktion, aber außer für eine kleine Gruppe von Fachleuten blieben Computer weitestgehend etwas Unbekanntes. Auch Fachleute mussten "Rechenzeit" an Rechnern reservieren und die Zeit effizient nutzen. In der Wissenschaft wurden solche rechenintensive Leistungen zunächst von mathematisch orientierten Disziplinen in Anspruch genommen. Hierzu gehört die Statistik.

Da vor allem in der englischsprachigen Archäologie seit längerem im Rahmen der Keramikklassifikation versucht worden war, statistische Ansätze an die Stelle subjektiver, erfahrungsgeleiteter Typologie treten zu lassen (Beschreibung des Prozesses seit den 1920er Jahren bei [@Vossen1970], verwundert es nicht, dass auch die frühesten Versuche der Umsetzung archäologischer Forschung mit dem Computer in der statistisch basierten Klassifikation zu suchen sind. Frühe Anwendungen zur Seriation werden angeführt bei Leblanc , sehr früh und mit grundsätzlichen statistischen Methoden hat der Autor der "Analytical Archaeology", David L. Clarke den Trend zur Statistik eingeleitet; er hatte schon 1962 für den Computer geeignete Keramikanalysen erstellt [@Clarke1962]. Allgemein wurde die statistisch begründete Klassifikation als "numerical taxonomy" bezeichnet, ein Begriff, den man aus der Biologie übernommen hatte -- denn die Biologie war und ist die normative Disziplin für archäologische Klassifikation [vgl. @Vossen1970]. So verwundert es nicht, das 1966 ein heute als Klassiker geltender Artikel zur numerischen Taxonomie in der Archäologie von einem Archäologen, einem Biologen, und dem Mitglied der "Experimental Programming Unit" an der Edinburgh University gemeinsam publiziert wurde [@HodsonEtAl1966]. Sowohl die theoretischen Grundlagen von archäologischer und klassifikatorischer Seit mussten von Fachleuten geklärt werden, aber die Durchführung musste speziell programmiert werden. -- Daneben begannen auch früh schon Versuche der automatisierten Seriation, von Leblanc [@LeBlanc1975a] für internationale Anwendungen angeführt; in Deutschland, wo Seriation gut in die Forschungslandschaft passte, wurden solche Algorithmen recht früh aufgegriffen [@weber2014] und weiter entwickelt (s.u.).

Kurz darauf untersuchte Whallon die Klassifikation einer Keramikgruppe mithilfe eines Entscheidungsbaums, für das er ein Computerprogramm entwickelte und in kleinerem Rahmen veröffentlichte [@Whallon1971], während die Klassifikation und die darunter liegende Methode heute besser zugänglich ist [@Whallon1972]. Zur selben Zeit veröffentlichte er einen Aufsatz zur Anwendung von Computern in der Archäologie, in dem er nicht nur vorhergehende Übersichten noch aus den 1960er zitieren kann, sondern schreibt: "The number and variety of computer applications in archaeology today are so great that it is virtually impossible to select any small number of individual projects as representative" [@Whallon1972a, 29]. -- Was damals sicher ein angemessener Eindruck war, mutet angesichts der heutigen, unübersichtlichen Situation ein wenig übertrieben an.

Neben Clarke und Whallon ist Dunnell zu erwähnen [@dunnell1971], sie haben vor allem im Bereich der Systematik (Klassifikation/Taxonomie, Modelle) an Grundlagen und Theorien gearbeitet, die eine unentbehrliche Grundlage für solide digitale Lösungen sind.

In Deutschland setzte eine ähnliche Entwicklung ebenfalls früh ein, so heißt es von dem Biostatistiker Peter Ihm, er habe seit Anfang der 1970er Jahre an verschiedenen westdeutschen Universitäten begonnen, Statistik für Archäologen zu unterrichten [@weber2014], und schon 1978 erschien sein Lehrbuch zur Statistik in der Archäologie [@ihm1978]. Auch die sehr frühe Anwendung einer statistischen Klassifikation sollte nicht vergessen werden [@dohrn-ihmig1976]. Anwendung und Weiterentwicklung von Klassifikation und Seriation blieb ein großes Thema in der deutschsprachigen Archäologie; für die Entwicklung digitaler Verfahren muss diese Entwicklung jedoch nicht weiter verfolgt werden.

Aus dieser Übersicht sollte eine Tendenz deutlich geworden sein: Noch vor der Umsetzung mit Computerprogrammen und während der ersten Jahre wurden theoretische Konzepte entwickelt, erst im Laufe dieses Prozesses wurden diese digital umgesetzt. Wissenschaftler:innen aus verschiedenen Disziplinen, vor allem der Biologie, haben hierfür zusammen gearbeitet, zunehmend haben jedoch Fachleute aus der Archäologie das Heft in die Hand genommen. Es wurden Lösungen für eine bestimmte Fundgattung entwickelt und publiziert, sodass weitere Kreise dann hierauf aufbauend eigene theoretisch-methodische Grundlagen erarbeiten und mit eigenen Entwicklungen digital umsetzen konnten.

### Archäologische Praxis? {#history-earlyarchaeologicalpractice}

1973 wurde die Gesellschaft "Computer Applications and Quantitative Methods in Archaeology Conference (CAA)" in Großbritannien von Susan Laflin gegründet. Sie war zunächst als Treffen von mathematisch und computertechnisch interessierten Archäolog:innen gedacht [@caa2023history] (s. @sec-history-caa) und passt somit vom Charakter in diese Jahre. Mittlerweile ist die CAA unverzichtbarer Bestandteil der archälogischen Forschungslandschaft.

Zur selben Zeit wurden in der Wirtschaft und anderen akademischen Disziplinen Computer als Werkzeug für fachspezifische Probleme genutzt und Lösungen entwickelt, die später in die Archäologie Eingang gefunden haben. Wie in der archäologischen Systematik, sind es zunächst Fächer, die mit Zahlen und "harten Daten" arbeiten: Vermessung und die Entwicklung von CAD, Karthographie, Chemie und die Auswertung chemischer Analysen in per Computer sind zu nennen, spielen aber vor 1980 in der Archäologie noch keine bedeutende Rolle; die Integration beginnt erst in der nächsten Phase.

Auch eine andere, heute zentrale Aufgabe des Computers setzt in der archäologischen Forschung erst später ein: die Nutzung von digitalen Datenbanken. Dem Design von Datenbanken liegen zwei Prinzipien zugrunde: Zum einen ist es der Inhalt oder das Thema der Datenbank -- zum Beispiel Bibliothekswissenschaften -- mit spezifisch inhaltlichen Erfordernissen und theoretischen Grundlagen, zum anderen ist es das Datenmodell, nach dem die jeweiligen Datenbanken eingerichtet werden. Während in der hier besprochenen frühen Zeit Daten zu Funden oder Befunden durchaus im Computer erfasst wurden, so geschah das fast ausschließlich projektgebunden, um z.B. eine bestimmte Analyse durchzuführen. Archivierung von Grabungen u.a. war noch sehr lange analogen Verfahren überlassen. Aber auch im Bereich Datenbanken sind um diese Zeit die Prinzipien entstanden, nach denen heute noch eine archäologische oder denkmalpflegerische Datenbank modelliert wird (s. @sec-teaching-applications, @sec-sample-datamodels).

### Zusammenfassung der frühen Jahre

Aus dieser Übersicht lassen sich einige Charakteristika der frühen Jahre ableiten.

-   Schon vor der Verbreitung von Computern wurden in der Archäologie Methoden diskutiert und getestet, die dann methodisch solide digital umgesetzt werden konnten, sobald Computer zur Verfügung standen.
-   Vor allem im Zusammenhang mit der "Verwissenschaftlichung" der Archäologie wurden bevorzug die Methoden angewendet, die sich für digitale Umsetzung eigneten, vor allem systematische, rechenintensive Aufgaben. Die theoretisch-methodischen Diskussionen wurden in Auseinandersetzung mit den seit den 1960er Jahren durchgeführten Studien fortgeführt.
-   Computer waren rar, teuer, schwierig zu bedienen; die Kenntnis naturwissenschaftlicher und mathematischer Grundlagen wurden als unverzichtbar erachtet, so dass Archäolog:innen zu Beginn meist gemeinsam mit Fachleuten aus den anderen Disziplinen -- vor allem der Biologie -- zusammen arbeiteten und gemeinsam Resultate von hohem wissenschaftlichen Wert vorweisen konnten.
-   Die jeweiligen Lösungen waren Insellösungen an einer bestimmten Fundgruppe oder Problematik; Nachbildungen mussten neu programmiert werden. Das bedeutet einerseits, dass die digitale Arbeit für die Archäologie nicht unbedingt zeitsparend war, aber es gab Raum für originelle, freie Entwicklung.
-   Viele Verfahren, die heute für die archäologische und denkmalpflegerische Arbeit bedeutsam sind, wurden zu dieser Zeit erst in ihren Grundlagen entwickelt und hatten keine Auswirkung auf die damalige archäologische Forschung oder Denkmalpflege. Die Grundlagen gelten jedoch nach wie vor, ihr Verständnis ist heute unabdingbar, um die neuen Entwicklungen korrekt anwenden zu können. Grundsätzlich sind die Beispiele, die damals mit großem Aufwand entwickelt und vorgestellt wurden, mit heute vorhandenen Daten, Hardware und Open Source Software, von Einzelpersonen in kurzer Zeit und ohne weitere Kosten durchführbar. Bildeten in der Frühphase die Darstellung der Methode neben dem Inhalt der jeweiligen Studien einen wichtigen Bestandteil der Arbeit, so kann man heute zunehmend auf etablierte Verfahren zurückgreifen und wieder die Feldarbeit und Interpretation der Analysen in den Mittelpunkt stelle (TODO Abschnitt unten hinzufügen?).
-   Insgesamt gibt es in der international zur Verfügung stehenden Literatur aus den Jahren bis in die 1980er Jahre nur wenige Namen, die immer wieder auftauchen; man kann es so verstehen, dass es eine kleine Elite gab, die zum einen die Bedeutung digitaler Entwicklungen für die Archäologie trotz ausstehender praktischer Vorteile einschätzen konnten, die genügend Fachkenntisse und Verständnis mitbrachten, um sich mit Fachleuten aus anderen Disziplinen zu unterhalten, und denen Computer für ihre Projekte zur Verfügung standen. **Solches tieferes Verständnis der theoretisch-methodischen Grundlagen und der digitalen Durchführung sollte in heutiger Lehrtätigkeit vermittelt werden.**
-   Die meisten Tätigkeiten in der Archäologie wurden nach wie vor analog durchgeführt: Zeichnung, Fotografie, Archivierung, Dokumentation, Publizieren.

## 1980 - 2000 Jahre {#sec-history-stages-ninetees}

### Technischer und kommerzieller Hintergrund

Schon im Verlaufe der oben beschriebenen frühen Jahre entwickelte sich die Computertechnologie in eine Richtung weiter, durch die ab den späten 1980er Jahren auch die archäologische Arbeit revolutioniert wurde: Anfang der 1970er Jahre fertigte IBM die ersten Mikroprozessoren in Serie, 1976 stellte Apple mit dem Apple I den ersten Personal Computer her, 1981 folgte der IBM-PC. Viele andere Unternehmen folgten mit ähnlichen Konzepten, die Nutzung der Maus und damit die Entwicklung von GUIs (Graphical User Interfaces) wurde ein wichtiges Charakteristikum der Arbeit am Computer. GUIs machten das Erlernen von kryptischen Befehlen überflüssig und ermöglichten die Nutzung von Computern einem weiten Personkreis über die Experten hinaus. Eine Reihe von Personal Computern wurden in den 1980er Jahren entwickelt, deren Namen heute noch bekannt sind -- wie Atari, Schneider, Commodore. Geblieben sind über die 1990er Jahre hinaus bis heute die "IBM-kompatiblen" Systeme, die neben den genutzten Prozessoren heute vor allem durch das gemeinsame Betriebssystem Windows von Microsoft charakterisiert werden können, sowie die Systeme der Firma Apple mit anderen Prozessoren und eigenem Betriebssystem als Vorläufer des heutigen Mac OS, einem Unix-Betriebssystem, dessen Entwicklung ebenfalls schon in dieser Stufe einsetzte.

1991 begann Linus Torvalds mit der Entwicklung des Betriebssystems Linux, einem freien Betriebssystem, das auch auf unterschiedlichen Rechnerarchitekturen arbeiten kann und wie Unix arbeitet. Es eignet sich für die Arbeit am Personal Computer, ist aber weltweit vor allem in Servern vorherrschend, die den Nutzer:innen nicht direkt begegnen. Die Entwicklung von Linux als offenem -- kostenlos und von jeder und jedem veränderbaren -- System ist im Rahmen der Entwicklung von Open Source zu sehen. Als Beginn der Open Source Bewegung wird das Anfang der 1980er Jahre von Richard Stallman initiierte GNU-Projekt zu gesehen [@gnu-proj2020, @stallman1985], das in aller Stille im Schatten der großen kommerziellen Erfolge anderer Software langfristig und nachhaltig wirkte und wirkt. Es hat einen ernormen Einfluss auf die Kultur der Softwareentwicklung, heute mehr als je zuvor. Der Begriff "Open Source" bedeutet nicht grundsätzlich "kostenlos" -- das ist nicht zwingend vorgegeben, wichtiger ist der Aspekt, dass der Quellcode offen ist, eingesehen und verändert werden kann. Solch kreativer Umgang mit Software ist bei proprietären Systemen wie den Office Paketen von Microsoft oder den Programmen der Adobe -- prominente Beispiele für die Mehrzahl von Software bei Strafe untersagt. Im Falle von Open Source kann jeder mitwirken, und das Urheberrecht der Beteiligten ist durch bestimmte Lizenzen gesichert, die noch in Kapitel [@sec-standardsqualifications] und angesprochen werden sollen.

Gegen Ende dieser Periode, nämlich 2005 wurde das Open Source Versionsverwaltungssystem "Git" publiziert, das seitdem ältere Versionsverwaltungssysteme weitgehend abgelöst hat. Es ist grundsätzlich für alle textbasierten Projekte geeignet und hat einen Prozess in Gang gesetzt, der in @sec-actual-situation-characteristics und @sec-community eingehend besprochen werden soll: Dieser vordergründig unscheinbare Bestandteil der Softwareentwicklung hat eine Arbeitsweise ermöglicht, die die Zukunft des digitalen Arbeitens auch in der Archäologie revolutioniert. In der hier diskutierten Zeit zwischen 1990 und 2010 war davon noch nichts zu spüren.

### Langfristig wirksame Software Entwicklungen

Ähnlich wie bei Linux und Git starteten in den frühen 1990er Jahren drei weitere wichtige Entwicklungen, die ihre volle Wirkung auf breitem Feld erst in den letzten zehn bis zwanzig Jahren entfaltet haben, und zum Teil indirekt, und auf unterschiedliche Weise.

Anfang der 1990er Jahre begann Guido van Rossum, die Programmiersprache Python zu entwickeln, die viele neue Programmierkonzepte enthielt [@wikipedia2023python] und relativ leicht zu erlernen ist. In der heute dritten Version ist Python kaum mehr wegzudenken aus der Arbeit mit Geographischen Informationssystemen. Gleichzeitig ist Python universell einsetzbar und nimmt im Bereich Statistik/Machine Learning heutzutage eine hervorragende Bedeutung ein. Dies war in in den ersten Jahrzehnten noch nicht absehbar.

In derselben Zeit wurde die professionelle und skriptbasierte Statistik Software R von den Neuseeländern Ross Ihaka und Robert Gentleman entwickelt [@wikipedia2023R]. Lange Zeit war das textbasierte Interface über einen kleinen Kreis von computeraffinen Experten hinaus nicht bekannt, ist heute aber im Bereich Statistik und Literate Programming mit Python zusammen das bedeutendste Programm für statistische Analysen. Für Archäologen ist das fokussiertere R sicher einfacher zu erlernen, ab über beide Programme wird noch mehrfach zu reden sein.

Das dritte zu nennende Programm ist LaTeX, die Entwicklung reicht schon in die 1980ger Jahre zurück [@wikipedia2023latex], flexibel einsetzbares Textverarbeitungs- und Satzsystem mit Markup-Sprache (s. @sec-software-classesofdataandprograms). Dabei kam ein Literaturverwaltungssystem zum Einsatz, das auch schon in den 1980er Jahren entwickelt wurde: BibTeX [@wikipedia2023bibtex]. Sowohl LaTeX als auch BibTeX mit einigen weiteren Entwicklungen werden auch heute noch direkt von einer computer-affine Clientel benutzt; sie werden aber aufgrund ihrer Komplexität kaum direkt von Nutzen sein für digitale Anwendungen in der Archäologie. Aber ohne mit LaTeX direkt in Kontakt zu kommen, sind beide Komponenten ausgesprochen wichtig geworden. Vielmehr werden sie bei der Transformation von Formaten benötigt sowie für die automatische Erstellung von Literaturverzeichnissen (@sec-software-classesofdataandprograms); das Schreiben im Textformat und Versionskontrolle, "Literate Programming" -- dies sind Stichworte, die noch das neue digitale Arbeiten in der Archäologie beschreiben und noch näher beschrieben werden.

### Anwendungssoftware und Betriebssysteme

Während die Entwicklungen um Git, Python, R und LaTeX/BibTeX wahrscheinlich in den 1990er und 2000er Jahren in weiteren Kreisen kaum bemerkbar waren, waren in diesen Jahren Fragen um das Betriebssystem und bestimmte Anwendungssoftware in der Öffentlichkeit und in der archäologischen Anwendung sehr präsent.

Lässt man die Workstations und ihre jeweiligen Betriebssysteme einmal beiseite, die in den 1980er und 1990er Jahren aufgrund ihrer besseren Rechenleistung gegenüber den PCs für anspruchsvolle Anwendungen verwendet wurden, so wurden die Welt der Personal Computer von einer kleinen Gruppe von Hardware-Produzenten und zwei Betriebssystemen beherrscht: Auf der einen Seite stand IBM und seine zunehmend erfolgreiche Konkurrenten wie Dell und Acer (neben anderen), auf deren Computern das Betriebssystem Microsofts Windows (zu Beginn noch auf MS-DOS basierend) und darüber die entsprechende Anwendungssoftware installiert wurde. Auf der anderen Seite Apple mit dem Betriebssystem Mac OS (heute OS X), das seit 2001 auf einem Unix Betriebssystem basiert.

Auf beiden Betriebssystemen lief zu Beginn unterschiedliche Anwendungssoftware, die zu großen Teilen im Laufe der Zeit auf das jeweils andere Betriebssystem portiert wurde, so dass es gegen Ende dieser Periode um 2010 herum kaum noch von Bedeutung war, welche Hardware und welches Betriebssystem man nutzte. Das war in dieser zweiten Stufe noch ein wichtiges Kriterium. Als Archäolog:innen kommt man natürlich zunächst mit der Anwendungssoftware in Berührung.

Zu den heutigen Platzhirschen zählt Excel von Microsoft, das zunächst in den 1980ern für Apple Computer entwickelt, dann aber auf Windows portiert wurde und auf beiden Systemen läuft. Im Bereich der Textverarbeitung hat sich Word weitgehend durchgesetzt, das zunächst auf Windows lief und später auf Apple / Mac portiert wurde. Bei der Bildverarbeitung lief Photoshop zu Beginn auf Apple, wurde auf Windows portiert, was einige Zeit die vorherrschende Plattform für Grafik und Design wurde. So wurde 1990 Photoshop für den Macintosh (Apple) herausgegeben, ebenso wurde das Zeichenprogramm Illustrator zuerst für den Mac, dann für Windows, wurde entwickelt. Beide Programme sind für die archäologische Arbeit sinnvoll, sie haben sich neben zahlreichen, oft überlegenen Konkurrenten auf beiden Betriebssystemplattformen durchgesetzt.

Die 1990er und die frühen 2000er Jahre können auch als "Kampf der Betriebssysteme" betitelt werden oder als "Kampf von OpenSource gegen die Vormachtstellung der proprietären Programme". Die Austauschbarkeit von Dateien, die auf Apple-Computern erstellt wurden mit solchen, die auf Windows-Computern erstellt wurden, war nicht garantiert, und zwar nicht einmal in identischen Programmen, die vom selben Hersteller auf den Markt kamen. Noch heute sind Office-Programme von Microsoft auf Windows zum Beispiel gegenüber der Office-Suite auf Macs mit mehr und professionelleren Möglichkeiten ausgestattet. Man kann das als Nachteil betrachten oder als Anreiz, die Welt von Microsoft Office zu verlassen und sich anderen professionellen Lösungen zuzuwenden, die dann vollkommen unabhängig von Betriebssystemen und gewinnorientierten Firmen sind; hierzu mehr in @sec-teaching-applications.

Zum "Kampf der Betriebssysteme" muss auch die besondere Rolle von Linux erwähnt werden: Über Jahre wurde versucht, die Desktop-Versionen als Alternative zu Apple und Windows zu etablieren, diese Bemühungen haben aber in der genannten Periode keine Früchte getragen, und es sieht so aus, dass in näherer Zukunft zwei große, von privaten Firmen angebotene Betriebssysteme den Markt der digitalen Archäologie bestimmen werden. Wir werden in einem späteren Abschnitt noch sehen, dass heute und in Zukunft allerdings die Anforderungen an die Software, auf allen Betriebssystemen gleichwertig zu laufen und standardisierte Daten zu speichern, sowie die zunehmende Bedeutung mobiler Geräte mit eigenen Betriebssystemen die klassischen Betriebssysteme als entscheidenden Bestandteil digitaler Arbeit vollkommen in den Hintergrund treten lassen werden (@sec-actual-situation).

Noch unter dem Paradigma der OpenSource Bewegung und unter dem Eindruck großer Softwareschmieden mit proprietären Programmen und Formaten, die einen Markt beherrschen, hattee sich die Bewegung um "OpenOffice", heute eher um dessen Ableger "LibreOffice" etabliert, die die Arbeitsweise von Microsoft Office-Programmen so zu kopieren versuchten, dass ein Umstieg leichter fiel. Trotz ihrer großen Leistungsfähigkeit hat sich LibreOffice bis heute nicht durchgesetzt; man kann über die Gründe diskutieren und sich fragen, ob es in näherer Zukunft überhaupt noch einen Bedarf für solche Office-Pakete gibt.

Diese vier Programmarten: **(1) Textverarbeitung** für das Verfassen von Aufsätzen, Hausarbeiten, Dissertationen etc. (faktisch vorwiegend in *Word)*, **(2) Tabellenkalkulation** für das Sammeln, Sortieren und Auswerten von Daten (faktisch vorwiegend in *Excel)*, **(3) Bildbearbeitung** und **digitales Zeichnen** (faktisch vorwiegend in *Adobe-Programmen)* für die Dokumentation von Befunden fanden schnell Eingang in die alltägliche Praxis -- vom Studium bis hin zur professionellen archäologischen oder denkmalpflegerischen Arbeit. -- Datenbanken wären in vielen Fällen besser geeignet als Excel, aber dies soll in einem gesonderten Kapitel diskutiert werden {@sec-software-classesofdataandprograms}.

Es handelt sich bei Anwendung dieser Programme **nicht** um die Einführung neuer Methoden mithilfe digitaler Programme, wie es die Umsetzung von statistischen Analysen der ersten Phase beispielsweise waren. Vielmehr werden **traditionelle Arbeitsschritte einfach digitalisiert**. Die Vorteile gegenüber den traditionellen Techniken wie Zeichnen mit Bleistift und Tusche oder Schreiben mit der Schreibmachine waren die Toleranz gegenüber Fehlern, Flexibilität der Arbeitsschritte, freie Gestaltung von Layouts und die Möglichkeit, "druckfertige" Ergebnisse ohne Handarbeit und effizient zu erstellen, ohne zusätzliche und zeitraubende Kommunikation mit Druckern, Zeichnern, Fotografen und anderen, die ursprünglich die archäologische Arbeit ergänzt und mit fachfremdem Expertenwissen abgeschlossen haben. Das Fehlen von Expertenwissen macht sich in manchen Arbeiten dieser Zeit durchaus mit schlechtem Layout oder intern schlecht aufgebauten Dateien bemerkbar. Gerade das Problem unprofessioneller Arbeit, die sich im abschließenden Druck nicht bemerkbar macht, war ein Charakteristikum dieser Zeit: Die tatsächlichen Vorteile, die die Arbeit mit dem Computer langfristig bietet, wurden hier konterkariert, da es oft nur darauf ankam, eine bisher analog erstellte Arbeit digital zu erstellen und dann analog zu archivieren; natürlich wurden auch die Dateien digital archiviert, an die weitere digitale Nutzung wurde dabei nicht gedacht, und für weitere Nutzung in anderen Projekten mit anderen Beteiligten waren diese Arbeiten nicht vorgesehen.

Viele dieser Probleme bestehen nach wie vor, und die Grundlagen, die in den Arbeiten jener Zeit schon fehlten, müssen heute nach wie vor unterrichtet werden; vor allem @sec-teaching-applications geht hierauf näher ein.

Anders als in der ersten, von Fachleuten und Fachproblemen geprägten Zeit, waren in dieser Stufe junge Menschen meist ohne fachliche Expertise -- weder in der Archäologie noch in Computeranwendungen -- für die Popularisierung digitaler Techniken verantwortlich. Dies war in allen Bereichen des akademischen und nichtakademischen Alltags in dieser Zeit der Fall; in der Archäologie aber war diese Entwicklung wegen des Bedarfs über viele Anwendugngsbereiche und die dilettantische Umsetzung besonders auffällig. Diese Phase der Popularisierung soll aber deswegen nicht abgewertet werden; wahrscheinlich war es ein notwendiger Schritt hin zu breiter und besser fundierter Anwendung. Sie hat nach wie vor noch nicht das notwendige professionelle Level erreicht, und dieses Buch soll Schritte in diese Richtung weisen.

### Professionelle Entwicklungen

Die Jahre zwischen 1990 und 2000 -- man kann diese Phase auch 10 bis 15 Jahre früher beginnen und 10 Jahre später enden lassen -- waren in anderen Fächern von grundsätzlichen Entwicklungen geprägt in Bereichen, die heute die archäologischen Fächer und die Gesellschaft insgesamt prägen: Kartographie und Geographische Informationssysteme, LiDAR, vernetzte Datenbanken, 3D-Vermessung und Umsetzung in Computermodelle und maßstabsgetreue analoge Modelle, statistische Verfahren und Visualisierungen, um nur einige zu nennen. Alle diese Bereiche sind heute aus der archäologischen Arbeit nicht mehr wegzudenken, sie waren damals allerdings mehr vom Hörensagen als von tatsächlicher archäologischer Anwendung bekannt.

Ausnahmen hiervon sind die Entwicklung von Grabungsdokumentationsmodulen für CAD-Programme, die schon in den frühen 1990er Jahren begann; hier sehen wir früh die Verknüpfung nicht-archäologischer Technologie mit archäologischen Aufgaben wie die im deutschsprachigen Raum verbreitete Software "ArchäoCAD". In diesen Bereich gehören auch 3D Entwicklungen in interdisziplinärem Zusammenhang [@ShinotoEtAl2002TopometricalmeasurementsTiryns]. An dieser Stelle ist auch Baoquan Song zu erwähnen, der früh digitale Verfahren für die Kartierung von Luftbildern in seine Arbeit integriert hat; hierfür war in den ersten Jahren noch eine Workstation und das privat nicht finanzierbare Programm ERDAS erforderlich; als Standardwerk hierfür ist der Band zur Luftbildarchäologie in China aus dem Jahr 2000 hervorgegangen [@LiPingel2000], neben zahlreichen anderen Arbeiten [@SongEtAl2019; @SongLeidorf2020]. Es versteht sich von selbst, dass diese Anwendungen erhebliche Kosten verursachten, anders, als die im vorherigen Abschnitt besprochenen populären, nicht fachgebundenen Softwares, und somit zwar fachlich genutzt, über die direkten Anwender hinaus jedoch nicht verbreitet sind.

### Die CAA (Computer Applications in Archaeology) {#sec-history-caa}

Die "Computer Applications and Quantitative Methods in Archaeology Conference (CAA)" wurde schon 1973 in Großbritannien von Susan Laflin als Treffen von mathematisch und computertechnisch interessierten Archäolog:innen gegründet wurde und heute eine international agierende Gesellschaft mit verschiedenen Publiaktionen und jährlichen Konferenzen ist [@caa2023history]. In dieser zweiten Phase setzte sie sich international als die maßgebende Veranstaltung für digitale Anwendungen durch und vereinigte die Möglichkeiten der technischen Entwicklungen mit fachlich soliden Fragestellungen und ihrer digitalen Umsetzung.

### Zusammenfassung {#sec-historical-stages-ninetees-character-problems}

Die zweite Phase ist gekennzeichnet durch Wachstum und Ausweitung.

-   Durch die Verbreitung des PC wurde Hardware und Software zugänglich für weite Teile, in den archäologischen Fächern nicht nur die professionelle Arbeit an spezifischen Anwendungen für die Archäologie, sondern auch für die Nutzung von Officeprogrammen, Fotobearbeitungssoftware und einfachen Datenbanken möglich wurde. Mit diesen Programmen war vieles -- von der Texterstellung bis hin zu statistischen Analysen oder Funddokumentation mit Fotos und Zeichnungen -- relativ einfach möglich, aber auch unangemessener Nutzung preisgegeben.

-   Vor allem zwei Betriebssysteme und ihre jeweils spezifische Software beherrschten lange Zeit den Markt; oft waren die Dateien nicht austauschbar. Hierdurch entstanden Kämpfe um die Vorherrschaft bestimmter Programme und Softwarefirmen, die weniger durch Qualität sondern die Masse der Verbreitung entschieden wurden. Proprietäre Datenformate beherrschten aus privatwirtschaftlichen Motiven das Feld.

-   Außerhalb der Archäologie wurde in unterschiedlichen akademischen und ingeneurtechnischen (TODO) Bereichen -- wie zum Beispiel in der Kartographie -- die Digitalisierung traditioneller Methoden vorangetrieben. Solche Lösungen fanden teilweise in gut ausgestatteten Projekten Eingang, aus denen sukzessive archäologisch verwertbare Lösungen entwickelt wurden. Diese hatten meist einen höheren Anspruch an Rechenleistung als auf PCs umsetzbar, sie waren von Fachleuten begleitet und solide entwickelt. Proprietäre Datenformate waren üblich, da die Entwicklung von Standards sich natürlicherweise der Entwicklung der eigentlichen Programme und Datenformate erst anschließt.

-   Entwicklungen, die früh in den 1990er Jahren oder früher begannen, blieben in der Archäologie weitgehend unbekannt, haben heute aber nicht zu unterschätzenden Einfluss auf die Arbeit mit dem Computer: Es ist die Entwicklung des rein textbasierten Satz- und Textverarbeitungssystem LaTeX mit seinem Prinzip der Trennung von Form und Inhalt, die Entwicklung der Programmiersprache Python, des Statistikprogramms R, sowie seit Anfang der 2000er Jahre des Versionskontrollsystems Git. Die Bedeutung dieser Entwicklung kann erst heute wirklich eingeschätzt werden.

-   Insgesamt und in der alltäglichen archäologischen Arbeit bliegen digitale Anwendungen auf kommerzielle, praktisch anwendbare Software mit proprietären Datenformaten beschränmt, der Austausch von Daten blieb nach wie vor ein schwieriges Unterfangen.

## 2000 - 2015 {#sec-historical-stages-2000s}

Die gut 20 Jahre zwischen der Jahrtausendwende und heute sind in vieler Hinsicht eine Übergangszeit; am Ende steht eine vollkommen gewandelte Situation, die ich im folgenden Kapitel (@sec-actual-situation) beschreiben möchte.

Die Übergangszeit ist durch einige wenige Ereignisse und Trends gekennzeichnet, die damals noch nicht unmittelbar Einfluss auf die Archäologie hatten, einige "early adaptors" in ihrer Arbeitsweise allerdings schon beeinfluss habe. Sie haben die Basis gelegt haben für eine Situation wie sie heute auch die Archäologie zu beeinflussen beginnt. Rückblickend sind dies mit Sicherheit die wichtigsten Punkte, die in einer Geschichte der Digitalisierung der Geisteswissenschaften und der archäologischen Fächer zu nennen sind.

### Ereignisse

-   2005 wird das verteilte Versionskontrollsystem "Git" veröffentlicht und publiziert (Übersicht in @wikipedia2023git; Homepage @homepage2023git). Ursprünglich für die Entwicklung des Linux-Kernels gedacht, war das System durch die Lizensierung mit der GNU General Public License frei, auch für andere Software-Entwicklungen zu nutzen. Es dauert nicht lange, bis die Möglichkeit, auch die Erstellung von Texten (HTML-Seiten, wissenschaftliche Texte mit Latex) und das gemeinsame Arbeiten mit getrennten Repos der Versionskontrolle mit Git anzuvertrauen, erkannt und genutzt wurde.
-   In der Folge entstehen zentrale Repo-Verwaltungen wie Bitbucket 2007 (Übersicht in @wikipedia2023bitbucket; Homepage @homepage2023bitbucket), GitHub 2008 (Übersicht in @wikipedia2023github; Homepage @homepage2023github), GitLab 2011 (Übersicht in @wikipedia2023gitlab; Homepage @homepage2023gitlab). Zu Beginn ist das Ausmaß, in dem diese Plattformen wenige Jahre später den Austausch von Programmen, Patches, und Ideen befördern, noch nicht absehbar.
-   2004 veröffentlicht John Gruber seine Syntax für eine reduzierte Markup-Sprache "Markdown" [@Gruber2004], [Übersicht mit Weiterentwicklungen: @wikipedia2023markdown]. Ursprünglich als einfache Entwicklungssprache für HTML-Seiten gedacht, hat sie sich zu dem System entwickelt, in dem heutzutage Texte erstellt werden, die nachhaltig lesbar, grenzenlos austauschbar und vielseitig formatierbar sind. Markdown ist aus der digitalen Arbeit nicht mehr wegzudenken und wird in kurzer Zeit auch die wissenschaftliche Textverarbeitung bestimmen. Es ist auch in den genannten Git-Systemen die Sprache, in der kommuniziert wird, und die Sprache, in der die Inhalte in Versionskontrolle erfasst werden.
    -   Hierzu entschieden beigetragen hat John McFarlane mit "Pandoc" [@homepage2022pandoc], einer zurückhaltenden und akademisch sinnvollen Erweiterung der Auszeichnungssprache Markdown mit der Möglichkeit, (a) aus etlichen anderen Formaten nach Pandoc und (b) von Pandoc in viele andere Formate zu konvertieren. Mehr dazu im nächsten Abschnitt und in @sec-software-fileformats. -- McFarlane konnte hierfür auf die Vorarbeiten mit LaTeX und BibTeX zurückgreifen, die dadurch erst ihre weite Verbreitung fanden -- ohne dass man direkt mit diesen Systemen arbeiten muss.
-   Von Markdown profitierte die Welt der "Notebooks" oder "Lab-Notebooks", in denen Text, Beobachtungen und Programme zusammengefasst wurden -- eine Idee, die auf dem Ideal des "Literate Programming" fußt. Für die beiden Programme, die oben schon als bedeutend für die digitale Archäologie genannt wurde -- R und Python -- sind die Notebooks ein grundsätzlicher Schritt hin zur weiten Verbreitung gewesen.
    -   Das 2014 ins Leben gerufene Jupyter-Project greift zurück auf iPython-Notebooks, die erstmals 2011 veröffentlicht wurden [@wikipedia2023jupyterproject, @homepage2023jupyterproject]. Es kann auch mit den Sprachen R, Julia und Python arbeiten, ist aber besonders stark im Bereich Python.
    -   Gleichzeitig lief eine ähnliche Entwicklung in der R-Welt: Nach dem Vorbild von Sweave – einer vom österreichischen Statistiker Leisch entwickelten Lösung, die Statistik mit dem proprietären R-Vorbild S und Textsatz mit TeX "verweben" konnte [@sweave2020] – hat Xie Yihui `knitr` entwickelt, ein System, das Markdown und R "zusammenstricken" kann. Die erste Version dieser damals schon ausgezeichneten Software war auf Github mit dem Tag "0.1" am 17. Januar 2012 gespeichert worden (https://github.com/yihui/knitr/releases/tag/v0.1) und wird lebhaft weiter entwickelt [@Xie2001]. Dies ist der Ursprung und die Basis von `RMarkdown`, einer erweiterten Form von Markdown, das (a) Codeblocks enthalten kann, die ausgeführt werden können, und (b) mithilfe von Pandoc in unterschiedliche Formate exportiert werden kann; hier können dann die Codeblocks ausgewertet mit Diagrammen, Tabellen und anderen Formen der Ergebnisdarstellung gespeichert werden [@XieEtAl2019, @homepage2023rmarkdownrstudio].
-   Die Entwicklungen von Xie führten zur Entwicklung von R Notebooks seit 2014/15, zu umfangreichen Möglichkeiten des Publizierens als Blog, Buch, etc., und seit 2022 liegt auf dieser Basis die Plattform "Quarto" vor, die nicht nur mit R, sondern auch mit Python sowie Julia und Observable arbeiten kann, zahlreiche flexible Formen des Publizierens und der Kooperation extrem vereinfacht, in einem logischen System zusammengeführt und bestens dokumentiert als Open Source zur Verfügung stellt (https://quarto.org). – Quarto führt schon in die gegenwärtige Situation über.

### Tendenzen

Die vielen Ereignisse, die im letzten Abschnitt beschrieben werden, mögen auf den ersten Blick unübersichtlich und unzusammenhängend wirken. Es sind Punkte in einer Entwicklung, die für uns in der Archäologie heute bedeutsam sind und durch ihr Zusammenwachsen zu einer neuen Qualität in der Arbeit führen, über das bloße Umsetzen analoger Arbeitsschritte in digitale Form hinaus. Die Tendenzen, gefiltert für archäologische Umsetzung, stellen sich wie folgt dar:

-   Reinem Text wird der Vorrang vor proprietären Formaten gegeben. Die Entwicklung von Unicode und Markup-Sprachen hat diesen logisch sinnvollen Trend ermöglicht (siehe @sec-actual-situation, @sec-software-fileformats).
-   Inhalt und Form werden getrennt betrachtet, dadurch lässt sich derselbe Inhalt in andere Formate und in anderen Kontexten nutzen.
-   Offenheit der Entwicklung und Austausch zwischen Interessierten weltweit auf Plattformen wie Github, Bitbucket, Gitlab hat der Vielfalt und Schnelligkeit von Entwicklungen, aber auch ihrer Zugänglichkeit einen Schub verliehen.
-   Ehemals kommerzielle Lösungen werden von Open Source Lösungen abgelöst, die unabhängig vom Betriebssystem frei nutzbar sind und weiter entwickelt werden können.
-   Standards und Übereinkünften kommen in dieser Vielfalt von Möglichkeiten eine zunehmende Bedeutung zu.

Diese Entwicklungen haben in den 2010er Jahren zu einer Ausweitung der Möglichkeiten digitaler Anwendungen in der Archäologie geführt, die heute das Bild bestimmen. Daneben darf nicht vergessen werden, dass auch hardwareseitig, zum Beispiel in Bereich digitaler Fotografie, Bildbearbeitung, 3D-Render, Luftbildarchäologie mit UAV, Prospektionen mit LiDAR usw. erhebliche Fortschritte gemacht wurden, so dass sowohl finanziell als auch in der Bedienung diese Expertenanwendungen einer breiteren Schicht erreichbarer wurden.

Die aktuell größte Aufgabe liegt darin, in den verschiedenen Entwicklungen das Wichtige vom Unwichtigen, Fundamentales von Vereinzeltem zu trennen, Anwendungsklassen und Muster zu erkennen, die sich wiederholen und sich in der Menge konkreter Angebote zu orientieren.

## Tabellarische Übersicht


+----------+-----------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
|          | Zeit      | Charakterisierung                                                        | Anmerkung                                                                                                                                     | Entwicklungen                                                                             |
+==========+===========+==========================================================================+===============================================================================================================================================+===========================================================================================+
| 1        | 1960      | Isolierte Fachstudien mit Expertenwissen                                 | -- Fachlich hervorragend                                                                                                                      | -- 1970er Jahre: Mikroprozessor                                                           |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          | bis       |                                                                          | -- Wegweisend für die Zukunft                                                                                                                 | -- Infragestellung der Vorteile der Expertenstudien innerhalb archäologischer Traditionen |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          | 1980      |                                                                          | -- "Pilotstudien"                                                                                                                             |                                                                                           |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          | -- Heute problemlos mit OpenSource nachbaubar                                                                                                 |                                                                                           |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          | -- Interdisziplinäre Kooperation bei gegenseitigem Verständnis                                                                                |                                                                                           |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          | -- CAA                                                                                                                                        |                                                                                           |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          | .                                                                                                                                             |                                                                                           |
+----------+-----------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| 2        | 1980      | Popularisierung und Spezialanwendungen                                   | -- PC                                                                                                                                         | -- GNU-Project                                                                            |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          | bis       |                                                                          | -- Populäre Office- und Zeichenprogramme                                                                                                      | -- OpenSource                                                                             |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          | 2000      |                                                                          | -- Professionelle, kostspielige Software für konkrete Anwendungen                                                                             | -- Linux                                                                                  |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          | .                                                                                                                                             |                                                                                           |
+----------+-----------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| 3        | 2000      | Wechsel zu Offenheit für "Nerds"                                         | -- Vordergründig weiter wie in Stufe 2                                                                                                        | -- git                                                                                    |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          | bis       |                                                                          |                                                                                                                                               | -- GitHub etc.),                                                                          |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          | 2015      |                                                                          |                                                                                                                                               | -- Markdown, Pandoc                                                                       |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          |                                                                                                                                               | -- R, Python, QGIS, ...                                                                   |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          |                                                                                                                                               | -- UAV, Luftbilder, LiDAR, ...                                                            |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          |                                                                                                                                               | .                                                                                         |
+----------+-----------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| 4        | seit 2015 | Zugänglichkeit, Offenheit, Professionalität, "unbegrenzte" Möglichkeiten | -- Entwicklungen der Vorjahre tragen Früchte (einfache Anwendbarkeit, zunehmende Popularisierung, tatsächliche Ablösung proprietärer Systeme) | -- Auflösung der Vormachtstellung der proprietären Lösungen aus Stufe 2?                  |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          | -- Verwirrende Vielfalt von hervorragenden Möglichkeiten                                                                                      |                                                                                           |
|          |           |                                                                          |                                                                                                                                               |                                                                                           |
|          |           |                                                                          | -- Wildwuchs von Standards, Regeln, Qualifikationen                                                                                           |                                                                                           |
+----------+-----------+--------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+

: Phasen in der Implementierung digitaler Werkzeuge in die Archäologie. {#tbl-stages}