# Über dieses Buch {.unnumbered}

## Anlass

Digital Humanities und digitale Anwendungen in den archäologischen Fächern sind im ständigen Umbruch begriffen -- es ist schwer, hier eine Übersicht zu behalten und auf aktuellem Stand zu bleiben. Dieses Buch soll Konstanten herausarbeiten, damit es leichter fällt, in Neuem das grundsätzlich Gültige wiederzuerkennen und sich ohne Umwege so weit anzupassen wie notwendig.

## Versionen

-   Begonnen September 2023, Outline.

## Links und Zitierweise

Maria Shinoto. (2023). Digitale Archäologie - Werkzeuge und Konzepte im Wandel. \[https://mariashinoto.github.com/digitialarchaeology.de\]. https://doi.org/10.5281/zenodo.8342718

```         
# Bibtex:

@book{maria_shinoto_2023_8342718,
  author       = {Maria Shinoto},
  title        = {{Digitale Archäologie - 
                 Werkzeuge und Konzepte im Wandel
                 (mariashinoto/digitialarchaeology.de)}},
  publisher    = {Zenodo},
  year         = 2023,
  month        = sep,
  doi          = {10.5281/zenodo.8342718},
  url          = {https://mariashinoto.github.com/digitialarchaeology.de}
}
```

## Über die Autorin

-   Privatdozentin am Institut für Ur- und Frühgeschichte und Vorderasiatische Archäologie, Zentrum für Altertumswissenschaften, Universität Heidelberg.
    -   Korrespondierendes Mitglied am Deutschen Archäologischen Institut
    -   Gastprofessorin an der Beppu University, Japan
-   Webseiten:
    -   [Institutsseite](https://www.uni-heidelberg.de/fakultaeten/philosophie/zaw/ufg/mitarbeiter/shinoto_maria.html)
    -   [Eigene Webseite](https://ac.shinoto.net)
-   Arbeitsschwerpunkte:
    -   Japanische Archäologie
    -   Keramik
    -   Digitale Anwendungen, insbesondere Statistik und Klassifikation
