# Übersicht

## Eine Analogie

Heute noch wird in der Archäologie viel mit Fotografie gearbeitet, und dieser Bereich ist ein guter Weg, ins Thema einzufinden. 

Es liegt noch nicht lange zurück, dass an archäologischen Instituten und auf Grabungen Zeichner oder Photographen gearbeitet haben, deren Aufgabe es war, für die Archäologen (es waren wohl weniger Archäologinnen) Aufnahmen zu machen, da sie die Tücken der analogen Technik (Filmauswahl, Farbstiche, Körnung, Beleuchtung, Schärfentiefe, Brennweiten...) zu beherrschen gelernt hatten. Sie haben Negative verwaltet, Abzüge erstellt und für Publikationen vorbereitet und archiviert, Angaben zu den Umständen der Fotografie und den abgebildeten Gegenständen oder Strukturen festgehalten -- heute würde man sagen: Metadaten. 

Seit Ende der 1990er Jahre wurde diese Technik langsam abgelöst, und heute, nach etwa einer Generation, sind diese Kenntnisse und Fertigkeiten nur noch in Ausnahmefällen gefragt. Sogar mit dem Smartphone lassen sich perfekte Aufnahmen durch Laien erstellen; Fehler werden fast ohne eigenes Eingreifen schon beim Fotografieren korrigiert: Belichtungsausgleich, Farbkorrektur, Verzerrung durch Objektive, Bildneigung -- alles wird sofort oder in einem automatisierbaren Schritt des "Postprocessing" korrigiert, für eine perfekte Tiefenschärfe können Aufnahmeprogramme in der Kamera direkt mehrere Aufnahmen stacken und ein in voller Tiefe scharfes Bild erstellen. Fotos, von Laien in einem kurzen Moment "aus der Hüfte geschossen" können informativer sein als manche aufwendig und mit großer Kenntnis erstellte Aufnahme aus früheren Zeiten.  

Natürlich geht dabei einiges verloren -- Unwichtiges und Wichtiges. Das Unwichtige heute sind vielleicht Kenntnisse zum Verhältnis von Brennweite und Ausprägung der Filmkörnung im Negativ oder den Einsatz von Filtern, um den Einfluss des Umgebungslichts auf den Film zu mindern -- um nur zwei Beispiele zu nennen. Aber es geht auch anderes verloren, was nachdenklich stimmt oder alarmieren sollte: Strahlen alte Aufnahmen nicht mehr Ruhe aus und laden ein zur genaueren Betrachtung? Sind die heutzutage berechneten Korrekturen tatsächlich glaubhaft? Wie platziert man ein Fundstück am besten für eine gute Aufnahme? Zudem wird Archäolog:innen eine weitere Verantwortung und Arbeitsschritte auferlegt: Fotografieren ist so einfach, warum nicht gleich selber machen? 

Auch die Verwaltung der Fotografien liegt nun mehr oder minder in der Hand der Archäolog:innen und auf ihrem Computer. Gab es für ausgebildete Fotografen erlernte Vorgaben, wie Negative, Kontaktabzüge und Abzüge aufzubewahren und zu katalogisieren sind, so strickt man sich heute eher selber eine Logik, in der digital abgelegt wird. Hierbei überlappen sich digitale Datenspeicherung, Datenbankentwicklung, Client-Server-Technologien, die genutzt werden können, um Fotografien zu speichern. Gleichzeitig sind Fotografien nicht mehr isoliert: Sie können in derselben Datenbank gemeinsam mit 3D-Daten, Zeichnungen, verbalen Beschreibungen und Schlagworten über mehrere, früher getrennte Bereiche hinweg verwaltet werden. 

Gemeinsame Verwaltung generisch unterschiedlicher digitaler Daten, gemeinsame Schlagworte, alles das sind Kennzeichen der Digitalisierung, die ganz neue Möglichkeiten der Verknüpfung und Sichtweisen ermöglichen, aber auch Probleme mit sich bringen: Waren früher Schlagworte zum Beispiel für Fotografien einer Institutssammlung festgelegt und über die Jahre weitergegeben worden, und galten sie nur für die Fotografie, so war dieses System für die Fachleute stressfrei beherrschbar. Heute gibt es übergreifende Systeme, und jeder Schritt in einem Bereich muss bedenken, welche Auswirkungen dies auf andere Bereiche hat. 

Hierfür sind Standards entwickelt worden, die an die jeweilige Situation im Institut angepasst werden können. Aber diese Standards selber sind komplex, müssen beherrscht werden und: Welchen Standard sollte man anwenden? Wie finde ich das Angebot von sinnvollen Standards?

Dieser kurz Überblick wird sicher auch Widerspruch hervorrufen, denn überall gibt es Situationen, die etwas anders geartet sind. Das soll uns nicht stören, denn in diesem Buch geht es darum, die grundsätzlichen Strukturen zu entdecken, das herauszuschälen, was strukturell gleich bleibt und verstanden werden muss. Hat man sich einmal in diese Strukturen eingearbeitet und hält sich in der eigenen Arbeit an diese Logik, so sind spätere Anpassungen kein Problem. Insofern sollte dieses Buch vor allem helfen, der nächsten Generation und den Unterrichtenden eine Orientierung zu geben bei folgenden Fragen: 

- Wie soll ich meine Daten sammeln und speichern?
- Welche Daten und Metadaten soll ich beachten? 
- Welche Möglichkeiten stehen mir jetzt für eine Datenbearbeitung zur Verfügung, welche Möglichkeiten sind für die Zukunft denkbar?
- Wie teile ich meine Daten mit der Community jetzt und in der Zukunft?



## Aufbau des Buches {#sec-bookstruct}

Fragen: Welche technischen Kenntnisse sind notwendig? Werden sie so einfach wie digitale Fotografie? Was geben wir auf, wenn wir der Oberfläche vertrauen und uns für eine Lösung entscheiden?

Um Konstanten zu erkennen, müssen wir erst einmal die Geschichte verstehen und dort Konstanten bis heute herausarbeiten. 

In zwei historischen Abschnitten werden Konstanten herausgearbeitet und heutige Zustände untersucht, um einen Ausblick in die Zukunft zu gewinnen. 

Im ersten Teil "Archäologie", wird die Geschichte digitaler Anwendungen in der Archäologischen Arbeit vorgestellt: Ausgrabung, Dokumentation, Klassifikation, Analysen, sowie damit verbundene Arbeiten wie Publizieren, Ausstellungen -- sowohl alleine als auch in Kooperation. Dieser Teil ist historisch aufgebaut, denn wir können die Anwendung digitaler Werkzeuge recht gut in mehrere, vollkommen unterschiedliche Phasen trennen, die aber recht gut durch die Konstanten in der Fragestellung und Wahl der Lösungsmethoden miteinander verbunden sind. 

In Teil 2 "Computer" werden Grundlagen zu Hard- und Software sowie der Softwareentwicklung (Design, Coding) vorgestellt, soweit sie das Verständnis für Konstanten, die über einzelne Anwendungen und Versionen von Software über Jahrzehnte erhalten bleiben, fördern. Bei der Softwareentwicklung ist ein wichtiger, von Laien wenig beachteter Aspekt neben dem eigentlichen Programm der, das sie auf Grundlagen aufbaut, die unabhängig von der Ausführung in digitalen Anwendungen schon immer bestanden haben. In einem geographischen Informationssystem gehören hierzu zum Beispiel Kenntnisse zu Geokoordinaten und Projektionen, oder in der Datenspeicherung das Design von Relationalen oder Hierarchischen Modellen. Diese Prinzipien werden hier nur kurz angesprochen und später in  @sec-teaching-foundations im Abschnitt zu vorgeschlagenen Unterrichtsthemen in verschiedenen Layern näher diskutiert. 

Ganz wichtig im Zusammenhang mit Computern und Digitalem sind aber zwei neuen Entwicklungen, die das Potenzial haben, weitere bedeutsame Konstanten zu werden: Die Community und die Explosion von Standards und Lizenzen. Die rasanten Entwicklungen vor allem der letzten zehn bis 15 Jahre sind vor allem der OpenSource Bewegung und dem kooperativen Austausch im Internet zu verdanken; beidem ist @sec-community gewidmet. Eine andere bedeutsame Entwicklung ist die akutelle Schwemme von Lizenzen und Standards beziehungsweise Regeln. Was sind tatsächlich Standards, die beachtet werden sollten? Welche Regeln sind hilfreich oder wichtig? Was ist aktuell, was ist nur eine Mode, was kann ich getrost außer Acht lassen? Auch das sind Fragen, die ohne Orientierung schwer zu beantworten sind und Lebenszeit auf Nebenschauplätzen kosten kann. 

Teil 3 zum "Unterricht" behandelt die Frage, was im Unterricht an archäologischen Instituten angeboten werden sollte. Hier wird ein Aufbau in verschiedenen Graden der Komplexität und Abhängigkeit von konkreter Software beziehungsweise konkreten Systemen vorgeschlagen. 

Das Kapitel zu den abstrakten Grundlagen (@sec-teaching-foundations) stellt unverändliche Konstanten vor, die man auch dann kennen sollte, wenn man selber kaum digitale Anwendungen nutzt und bei Bedarf auf Fachleute zurückgreifen kann. Gerade für die Dialoge und die Kooperation mit Fachleuten sind einige Grundkenntnisse hilfreich, die eine echte Kommunikation erst ermöglichen. 

Im folgenden Kapitel zu Anwendungen (@sec-teaching-applications) werden die wichtigsten konkreten Anwendungen und Software angesprochen, die im Rahmen archäologischer Arbeit bedeutsam werden können. Es gibt hier seit "Ewigkeiten" bestehende proprietäre Lösungen für einfache Fragen wie Microsoft's Office Pakete für Datenspeicherung mit Access oder Excel, Analysen mit Excel, Vorbereitung von Publikationen und Vorträgen mit Word und Powerpoint, die mit Sicherheit noch lange eine Rolle spielen werden, da sie vor allem in der Wirtschaft nicht mehr wegzudenken sind. 

Direkt konkurrierende Produkte sie LibreOffice sind eine nicht immer ebenbürtige Alternative, aber die tatsächlichen Alternativen sind in Entwicklungen der letzten knapp 20 Jahre im OpenSource-Bereich zu suchen, und die Ablösung der Arbeit mit Office Paketen ist ein erster Schritt in die produktive und zeitgemäße Nutzung digitaler Anwendungen. Dies gilt für das Schreiben und Datenspeichern in reinen Textformaten, die nahtlos in verschiedene professionelle Analyse-Anwendungen aus dem OpenSource-Bereich führen. Das gilt aber auch für die Ablösung von proprietären Statistik- und GIS-Programmen sowie 3D Anwendungen durch professionalle und bedienbare Lösungen aus dem OpenSource-Bereich, die ihre kommerzielle Konkurrenz zum Teil schon hinter sich gelassen haben. 

Die Diskussion dieser Problematik und konkreter Software oder Systeme ist einer der Kernpunkte dieses Buchs. Es wird sicher der Bereich sein, der am ehesten veraltet, denn die Entwicklung im OpenSource Bereich ist atemberaubend. Daher sollen hier immer Versionsnummern, Links und Daten genannt werden, damit die Aktualität und Gültigkeit der Aussagen überprüft werden kann. Trotzdem: Anhand der Diskussion und Beispiele sollen Prinzipien und Konstanten diskutiert werden, es handelt sich nicht um Tutorials für den Umgang mit konkreter Software. -- Eine gewisse "Haltbarkeit" der Aussagen sollte also erwartet werden. 

Der letzte Teil bringt drei Beispiele für Probleme, die in verschiedenen Layern unterrichtet werden können: (1) Prinzipien von Datenmodellen - Datenmodellierung für statische Datenbanken - Datenmanipulation und Ändern von Modellen in statistischer Software; (2) das Schreiben alleine oder im Team mit Textverarbeitungen und Tracking - Schreiben im Textformat mit variablem Output - Schreiben mit Versionskontrolle - Schreiben mit Versionskontrolle im Team - integriertes Forschen und Schreiben (Literate Programming); (3) Kooperation und Integrations verschiedener Ansätze. -- Mit diesen Themen wird nur ein Ausschnitt digitaler Anwendungen in der Archäologie besprochen, immer unter dem Aspekt der Konstanten und des "Wiedererkennungswerts"; weitere Anwendungen wie 3D Vermessungen und Rekonstruktionen, Prospektionen mit unterschiedlichen Methoden und Geräten u.a. sollte aktuellen Tutorien vorbehalten bleiben (TODO Link zu DiKopA). 

---
TODO Illustrationen